### ISSUE TITLE
请问有没有的办法改变Debian的安装路径和工作的默认储存路径

### ISSUE THREAD

**Issue by maxwelldemon5119** [DongboShi/bigdata_econ#10]
在Microsoft Store下载的Debian默认安在C盘某处，进行的活动也都会在C盘保存，请问有没有成熟的方法改变Debian的安装路径和相关工作文件保存的路径

**Comment by chenjiancqu** [comment]
可以尝试一下更改默认应用安装位置：

打开“设置”应用。
转到“系统” > “存储” > “高级存储设置” > “更改新内容的保存位置”。
在“新应用将保存到”选项中，选择您想安装 WSL 的驱动器。
