### ISSUE TITLE
关于MacOS执行curl指令，显示curl: (28) Failed to connect to patents.google.com port 443 after 75234 ms: Couldn't connect to server

### ISSUE THREAD

**Issue by huang-zhiming** [DongboShi/bigdata_econ#12]
问题描述：在网页上可以打开谷歌专利相关页面，但无法使用curl指令获取
已排除 Network Connectivity、 Firewall Settings问题，已尝试Use a Different DNS Server、Use IP Address Instead of Domain Name 结果都不成功，报错提示都是curl: (28) Failed to connect to patents.google.com port 443 after 75234 ms: Couldn't connect to server
如图
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/769b2c62-4120-4944-8044-c13536de6390)

**Comment by DongboShi** [comment]
把你的vpn设置为全局代理

**Comment by DongboShi** [comment]
你试一下能不能ping 通 谷歌地址

**Comment by huang-zhiming** [comment]
我的VPN是全局代理，但是ping不通谷歌，可以ping百度

**Comment by DongboShi** [comment]
https://apple.stackexchange.com/questions/226544/how-to-set-proxy-on-os-x-terminal-permanently

**Comment by DongboShi** [comment]
要配置一下命令行环境来使用代理

**Comment by huang-zhiming** [comment]
proxy username 和password 是啥啊？

**Comment by huang-zhiming** [comment]
我刚刚查看了一下我的proxy没有username 和password，所以这条命令export http_proxy="username:password@ip address:port number"我不知道怎么改了

**Comment by huang-zhiming** [comment]
可以了，感谢万能的老师和助教们
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/8436f307-2146-4a0b-be33-2bfcbfd6d2f4)
