### ISSUE TITLE
git add文本后 一直提示这个指令，无法git commit

### ISSUE THREAD

**Issue by hahasyj** [DongboShi/bigdata_econ#13]
![bea9abf1d199897d6f648f2903e8009](https://github.com/DongboShi/bigdata_econ/assets/152355780/d5fac1be-308d-429a-8c0a-9ae90abb285f)

**Comment by hahasyj** [comment]
后面git push之前也遇到相似问题
![Uploading 5e129c3317742236778619628bb7fd6.png…]()

**Comment by DongboShi** [comment]
你这个不是成功了吗？

**Comment by hahasyj** [comment]
啊啊啊 他一直提示我让我Git rm --cached ,后面git push 一直没法push上去

**Comment by wuvickychina** [comment]
一样遇到git push 不上去，需要输入github账号密码，但是密码输不进去，显示：
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/wuvickychina/learngit.git/'

**Comment by chenjiancqu** [comment]
git remote set-url origin git@github.com:username/repo.git
username 和 repo 应该被替换为你 GitHub 用户名和希望连接到的存储库的名称。

**Comment by zhazhadz** [comment]
git clone的时候你用的是http,remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/wuvickychina/learngit.git/这句话的英语翻译一下就是不要用HTTP，git clone,要用ssh
