### ISSUE TITLE
git clone时出错

### ISSUE THREAD

**Issue by shirleychen0124** [DongboShi/bigdata_econ#14]
执行git clone https://github.com/shirleychen0124/paper-reading.git

显示【致命错误：无法访问 'https://github.com/shirleychen0124/paper-reading.git/'：Recv failure: Operation timed out】

请问这是由于vpn设置而产生的问题吗？

谢谢！

**Comment by DongboShi** [comment]
试一下  git clone ssh 那个链接

**Comment by shirleychen0124** [comment]
可以了，谢谢老师！
