### ISSUE TITLE
关于Rstudio 整数判断错误

### ISSUE THREAD

**Issue by huang-zhiming** [DongboShi/bigdata_econ#16]
问题描述，Rstudio无法正常判断整数，输出结果全部为“FALSE",如图示：
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/d7688dbf-2445-4eab-9502-6e0798508f4d)

**Comment by DongboShi** [comment]
为了避免歧义（懒），R直接假定所有的数字都是numeric。你试一下is.integer(as.integer(3))

**Comment by huang-zhiming** [comment]
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/30736aa7-9cef-4dde-b521-bbf742ca3e40)
果然！！！
