### ISSUE TITLE
关于如何使用name(x)去掉向量中单个元素的元素名

### ISSUE THREAD

**Issue by huang-zhiming** [DongboShi/bigdata_econ#17]
问题：当使用name(x)的时候x代指的是numeric数值？还是向量中的位序？还是元素名本身？但三者都报错。
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/5b7e7bf0-e429-45c2-b1a9-7f92112466ce)

**Comment by huang-zhiming** [comment]
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/3e671bd2-c7d4-4e0f-b721-d029b39a56af)
没有报错了，但去除元素名失败

**Comment by huang-zhiming** [comment]
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/bd35f533-27a3-4a5f-899c-c10fee973251)

**Comment by huang-zhiming** [comment]
替换元素名字是可以的
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/2726dfaa-b256-4e06-92c0-df409965a446)

**Comment by DongboShi** [comment]
你要是不贴出来代码，我是真的不想管你。。

**Comment by huang-zhiming** [comment]
啊对不起(＞人＜；)
代码是：
> ages['赵四'] <- 51
> ages["赵四"]
赵四 
  51 
> ages
赵四 刘能 ⻓贵 
  51   55   58 
> names(ages)[names(ages) == "赵四"] <- "张三"
> ages
张三 刘能 ⻓贵 
  51   55   58 
> names(ages)[names(ages) == "张三"] <- NULL
Error in names(ages)[names(ages) == "张三"] <- NULL : replacement has length zero

**Comment by DongboShi** [comment]
元素的名字是一个向量，NULL表示“空”，不能作为一个向量的元素

**Comment by DongboShi** [comment]
如果你非要向量的某一个元素没有名字，那么可以用NA来赋值

**Comment by huang-zhiming** [comment]
原来如此，谢谢老师~~
