### ISSUE TITLE
在R中尝试使用last()函数，但报错

### ISSUE THREAD

**Issue by shirleychen0124** [DongboShi/bigdata_econ#18]
尝试用last(v1)取出v1的最后一个元素，但显示：
Error in last(v1) : could not find function "last"

请问是需要另外安装last()函数包吗？（知道有其他方式可以实现取末位值，只是好奇为什么用last会报错，检索了一些教程都是可以直接用last函数）

谢谢！

**Comment by DongboShi** [comment]
library(dplyr)
