### ISSUE TITLE
shebang语句报错：/usr/bin/env: ‘Rscript\r’: No such file or directory

### ISSUE THREAD

**Issue by hanxiake000** [DongboShi/bigdata_econ#19]
在命令行中尝试用两种方法调用Rscript。
第一种： “Rscript ./add.R 3 4”运行正常；
第二种：在R文件中添加shebang语句“#! /usr/bin/env Rscript”，再运行“./add.R 3 4”，会出现如图错误，不知道根据它的报错提示具体应该怎么操作。
另外，我的R文件后缀是大写的R，原代码里都是小写r，运行不了，所以我把代码里所有的.r改成了.R，不知道报错是不是和这个有关。

![微信截图_20231203182349](https://github.com/DongboShi/bigdata_econ/assets/151877272/cfd3bba8-c5bc-4133-8d02-23233adea9ac)

**Comment by DongboShi** [comment]
ls -l /usr/bin/env的输出是啥

**Comment by DongboShi** [comment]
whereis R也试一下

**Comment by DongboShi** [comment]
哦我知道了，你的脚本使用了windows风格的换行符"\r"
https://copyprogramming.com/howto/how-to-fix-env-bash-r-no-such-file-or-directory-error-in-unix-and-linux-systems

**Comment by hanxiake000** [comment]
> 哦我知道了，你的脚本使用了windows风格的换行符"\r" https://copyprogramming.com/howto/how-to-fix-env-bash-r-no-such-file-or-directory-error-in-unix-and-linux-systems

确实是这个问题！按照链接里的方法已经解决，谢谢史老师！
