### ISSUE TITLE
Rstudio结果栏跑不出结果

### ISSUE THREAD

**Issue by gaoly123** [DongboShi/bigdata_econ#20]
输入function函数，结果栏只是复制了命令，没有结果
![1701750791912](https://github.com/DongboShi/bigdata_econ/assets/152077763/8f0dfbc3-35c4-4aa3-b922-ff14dc774b7a)
![1701750857775](https://github.com/DongboShi/bigdata_econ/assets/152077763/8046dd62-2590-428c-9e74-10fd7d8024ea)

**Comment by DongboShi** [comment]
用control + C先把命令结束掉。
这个加号表示前面的某个命令没有结束

**Comment by gaoly123** [comment]
老师，是直接在命令后按control+C吗？按了但毫无反应，还是需要选中这个命令再按control+C，按了也毫无反应，再次运行还是复制命令

**Comment by DongboShi** [comment]
要在运行界面control+c先结束掉你前面的代码
