### ISSUE TITLE
将代码封装成为一个可以在命令行运行的脚本，脚本的唯一一个参数为aminer论文文件所在的路径

### ISSUE THREAD

**Issue by denghui123** [DongboShi/bigdata_econ#21]
老师，这个完全没思路，也根据课件、资料尝试了一些方法，结果更混乱了。不知道咋弄了，需要老师提供一点思路和步骤。谢谢啦

**Comment by DongboShi** [comment]
比如你用commandArge将命令行参数中的路径读入

**Comment by denghui123** [comment]
> 比如你用commandArge将命令行参数中的路径读入

args <- commandArgs(trailingOnly = TRUE)
path <- args[1]
args <- c("D:/桌面/work1/Aminer_data")
path <- args[1]
print(path)

老师，是这样吗？这样传递了这个路径，但是2中的代码怎么给放进去呢

**Comment by DongboShi** [comment]
不是的，你再看看例子

**Comment by denghui123** [comment]
> 不是的，你再看看例子

噢，谢谢老师。我说我怎么R脚本都运行不了呢，原来我在不同的界面
