### ISSUE TITLE
使用commandArgs报错

### ISSUE THREAD

**Issue by HengfeiMa95** [DongboShi/bigdata_econ#23]
![WeChat7c090f6b518340a274202f2be9f3f2b0](https://github.com/DongboShi/bigdata_econ/assets/152389515/3e2ae791-e278-4fa9-803a-6f51e39c2d4c)
在调用R环境后，按照课件中的命令args = commandArgs(T) ，报错no matches found，是不是需要每个命令前都加调用R命令？
搜gpt给出一个新的代码是Rscript -e 'args <- commandArgs(trailingOnly = TRUE); print(args)'不确定是否正确，因为继续对mn定义的时候又报错zsh: number expected

**Comment by DongboShi** [comment]
args = commandArgs(T)是写在R脚本里面的
