### ISSUE TITLE
如何将Git与GitHub重新建立联系

### ISSUE THREAD

**Issue by maxwelldemon5119** [DongboShi/bigdata_econ#25]
我在写完.R文件后准备push，一开始进行git push时出现认证问题，之前输一长串Token代替密码可以成功push，但这次输入Token作为密码后失败了，遂开始按issue#4 的方法调整认证方法。
![18f9732aaaee5281af5743aa65f462b](https://github.com/DongboShi/bigdata_econ/assets/152062733/09b19488-ac9e-4e86-bad8-9fc836803b15)
按issue#4 的指示重新生成token后，用git remote set-url origin https://<token>@github.com/maxwelldemon5119/repository.git命令后，再用git push origin master后开始报错：
![6e15d0f85df677ea8c1468232f028a2](https://github.com/DongboShi/bigdata_econ/assets/152062733/fd39f218-a284-43e4-abdd-9e1731507b53)
之后用了git init、git remote rm origin，现在git remote -v返回空值，不知道如何与github正确建立联系了，请指示
![6e15d0f85df677ea8c1468232f028a2](https://github.com/DongboShi/bigdata_econ/assets/152062733/69bc6f65-0d1d-4c40-b20f-65d85eea72fc)

**Comment by DongboShi** [comment]
你clone成功了吗

**Comment by linyanbruce** [comment]
你好，我是#4的作者，昨天我也遇到了类似的情况
把这个目标仓库的https地址换成ssh的格式，只要之前token设置成功（且没有过期），还是可以push上去的（虽然我也有部分报错没解决），但是实际操作成功了。
我猜测这可能和`git clone`后面放的是http还是ssh可能有关系 影响了fetch和push的地址设置

**Comment by huang-zhiming** [comment]
我也是同样的问题，使用命令“git remote set-url origin +SSH字符串”（在remote repository code那里找SSH字符串）替换http创建本地repository和remote repository的链接，运行后再git push即可

**Comment by maxwelldemon5119** [comment]
> 你clone成功了吗

昨天clone成功了。
我刚刚按照楼下两位同学的指示，用git remote set url origin+ SSH, 成功push了，问题解决

**Comment by maxwelldemon5119** [comment]
> 我也是同样的问题，使用命令“git remote set-url origin +SSH字符串”（在remote repository code那里找SSH字符串）替换http创建本地repository和remote repository的链接，运行后再git push即可

非常有用，非常感谢！

**Comment by maxwelldemon5119** [comment]
> 你好，我是#4的作者，昨天我也遇到了类似的情况 把这个目标仓库的https地址换成ssh的格式，只要之前token设置成功（且没有过期），还是可以push上去的（虽然我也有部分报错没解决），但是实际操作成功了。 我猜测这可能和`git clone`后面放的是http还是ssh可能有关系 影响了fetch和push的地址设置

确实，操作后现在再git remote -v后返回的都是SSH了，所以一切正常了，非常感谢
