### ISSUE TITLE
安装pycharm无法设置虚拟环境变量

### ISSUE THREAD

**Issue by lindingkang** [DongboShi/bigdata_econ#26]
跟着视频教程来做，在设置virtualenv时，我在我的目录/home/penpen下创建了/home/penpen/github/python311，并选择了这个路径。报错信息如下。目前还没有尝试什么解决办法，没有搜到同样的错误。
![image](https://github.com/DongboShi/bigdata_econ/assets/152069389/ac52f080-efd4-4a09-a9f8-cfb80b120d7b)

**Comment by lindingkang** [comment]
这个路径的错误好像跟wsl的localhost有关系，在前一步wsl distribution introspection的时候，显示的wsl:好像是同一个乱码
![image](https://github.com/DongboShi/bigdata_econ/assets/152069389/139ac0a9-40c7-45d3-8430-ce60c3ff86ab)

**Comment by hanxiake000** [comment]
我也是一模一样的问题，等一个solution。

**Comment by DongboShi** [comment]
你先看下 whereis python

**Comment by lindingkang** [comment]
在wsl里面输入`whereis python`
输出`python:`
![image](https://github.com/DongboShi/bigdata_econ/assets/152069389/30927996-f480-47a8-ad3d-f77904baa9b8)

在cmd里面输入`where python`
输出`C:\Users\林北鸣\AppData\Local\Programs\Python\Python37\python.exe
C:\Users\林北鸣\AppData\Local\Microsoft\WindowsApps\python.exe`
![image](https://github.com/DongboShi/bigdata_econ/assets/152069389/28a67bc8-82ed-41e5-9670-fd30739e17d7)

**Comment by DongboShi** [comment]
和cmd没关系

**Comment by DongboShi** [comment]
你的wsl有python吗

**Comment by lindingkang** [comment]
我没有自己安装过，但是使用如下代码返回了python的版本。
在wsl里面输入`python3 --version`
输出`Python 3.11.2`
![image](https://github.com/DongboShi/bigdata_econ/assets/152069389/961b0978-0135-46fb-ac20-a4c4393c917b)

**Comment by DongboShi** [comment]
现在看起来是你的路径无法识别，你系统路径上的中文都改成英文试试

**Comment by DongboShi** [comment]
https://zhuanlan.zhihu.com/p/614393925

**Comment by hanxiake000** [comment]
可能不是中文字符的原因，我是全英文的路径，也是同样的问题，后来我发现的debian界面有一句话“wsl: 检测到 localhost 代理配置，但未镜像到 WSL。NAT 模式下的 WSL 不支持 localhost 代理”，感觉是这个问题，就搜了到一个解决方案https://github.com/microsoft/WSL/issues/10753，跟着最新的那个回答操作，debian中那句话就没了，pycharm创建环境也成功了。你看看你的debian有没有这句话，有的话可以试一下那个链接里的方案。


![微信截图_20231206191508](https://github.com/DongboShi/bigdata_econ/assets/151877272/0df9789b-865e-4d78-96b8-ecd7c1897d50)
![微信截图_20231207183749](https://github.com/DongboShi/bigdata_econ/assets/151877272/2945ee4b-199d-4a4c-aada-90723d2dcd0e)

**Comment by lindingkang** [comment]
> 可能不是中文字符的原因，我是全英文的路径，也是同样的问题，后来我发现的debian界面有一句话“wsl: 检测到 localhost 代理配置，但未镜像到 WSL。NAT 模式下的 WSL 不支持 localhost 代理”，感觉是这个问题，就搜了到一个解决方案[https://github.com/microsoft/WSL/issues/10753，跟着最新的那个回答操作，debian中那句话就没了，pycharm创建环境也成功了。你看看你的debian有没有这句话，有的话可以试一下那个链接里的方案。](https://github.com/microsoft/WSL/issues/10753%EF%BC%8C%E8%B7%9F%E7%9D%80%E6%9C%80%E6%96%B0%E7%9A%84%E9%82%A3%E4%B8%AA%E5%9B%9E%E7%AD%94%E6%93%8D%E4%BD%9C%EF%BC%8Cdebian%E4%B8%AD%E9%82%A3%E5%8F%A5%E8%AF%9D%E5%B0%B1%E6%B2%A1%E4%BA%86%EF%BC%8Cpycharm%E5%88%9B%E5%BB%BA%E7%8E%AF%E5%A2%83%E4%B9%9F%E6%88%90%E5%8A%9F%E4%BA%86%E3%80%82%E4%BD%A0%E7%9C%8B%E7%9C%8B%E4%BD%A0%E7%9A%84debian%E6%9C%89%E6%B2%A1%E6%9C%89%E8%BF%99%E5%8F%A5%E8%AF%9D%EF%BC%8C%E6%9C%89%E7%9A%84%E8%AF%9D%E5%8F%AF%E4%BB%A5%E8%AF%95%E4%B8%80%E4%B8%8B%E9%82%A3%E4%B8%AA%E9%93%BE%E6%8E%A5%E9%87%8C%E7%9A%84%E6%96%B9%E6%A1%88%E3%80%82)
> 
> ![微信截图_20231206191508](https://private-user-images.githubusercontent.com/151877272/288734244-0df9789b-865e-4d78-96b8-ecd7c1897d50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTU1NzAsIm5iZiI6MTcwMTk1NTI3MCwicGF0aCI6Ii8xNTE4NzcyNzIvMjg4NzM0MjQ0LTBkZjk3ODliLTg2NWUtNGQ3OC05NmI4LWVjZDdjMTg5N2Q1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QxMzIxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWQ4Y2U2YzhlMDYyMzQzYjE2MmI5ZWMxNzE3ZDgxNmZkOGEyYTJlYmM0ZDNlNjk0MWU1ODc2ZjIwYzFkODkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jwIre2Iigdwl-iKTN2iMaR0GtG2M2iwzoT9p9NERtv8) ![微信截图_20231207183749](https://private-user-images.githubusercontent.com/151877272/288734253-2945ee4b-199d-4a4c-aada-90723d2dcd0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTU1NzAsIm5iZiI6MTcwMTk1NTI3MCwicGF0aCI6Ii8xNTE4NzcyNzIvMjg4NzM0MjUzLTI5NDVlZTRiLTE5OWQtNGE0Yy1hYWRhLTkwNzIzZDJkY2QwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QxMzIxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzBkMzEzYjlkYmU3MmQ0MzNjYWUwYmMxODJiZDRkZjY0OWYxNmEyNThmNDM0MmY2YjhhY2VlZmUyM2JmOWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6UxwWY7nA-Uj3fEPwkU2b4YDNyT3LTuukYsoBfY-Ego)

这个方法成功了，非常感谢！我把方法粘过来：
1. Open or create the wsl configuration file (located at `%USERPROFILE%\.wslconfig`), and enter the following content:  

`[experimental]`

`autoMemoryReclaim=gradual  # gradual  | dropcache | disabled`

`networkingMode=mirrored`

`dnsTunneling=true`

`firewall=true`

`autoProxy=true`

3. Open the command prompt and execute `wsl --shutdown`

**Comment by DongboShi** [comment]
补充一个点，就是wsl --shutdown要在cmd环境里面运行
