### ISSUE TITLE
list.files读不出文件

### ISSUE THREAD

**Issue by gaoly123** [DongboShi/bigdata_econ#28]
![1701850734611](https://github.com/DongboShi/bigdata_econ/assets/152077763/70a06e22-4704-4e99-aa2c-87ccf9ae8436)
![1701850782377](https://github.com/DongboShi/bigdata_econ/assets/152077763/cb35ed4c-dbba-430e-8fa6-3f2eafd66619)
老师，是Windows系统，是否是路径输入错误

**Comment by DongboShi** [comment]
就是路径错误
