### ISSUE TITLE
因为Git pull一直连不上，把git --global http给改了，然后git pull和git push都连不上了，不知道怎么复原

### ISSUE THREAD

**Issue by lindingkang** [DongboShi/bigdata_econ#3]
Git pull打开vpn还是关闭vpn都连不上，显示的错误不同。然后在csdn上找教程，就把git --global http的参数给改了，代码如下：
`git config --global https.https://github.com.proxy https://127.0.0.1:7890 `
`git config --global https.https://github.com.proxy https://127.0.0.1:7890 ` 
`git config --global http.proxy 'socks5://127.0.0.1:7890'  `
`git config --global https.proxy 'socks5://127.0.0.1:7890'`
然后git push和gitpull都连不上了。报错信息都是这个：
`fatal: unable to access 'https://github.com/lindingkang/learngit.git/': Failed to connect to 127.0.0.1 port 7890 after 1 ms: Couldn't connect to server`
尝试了一下把git卸载了重新装，好像不行，报错还是说无法链接到127.0.0.1
不知道从哪开始了解这个问题，没有懂网络连接的整个问题，在装wsl的时候就有好多次因为网络出错，也没懂--global变量，看了man里面讲的也没详细讲。

**Comment by DongboShi** [comment]
首先不推荐在csdn找教程，很多是坑。
试一下git config --global --unset http.proxy

**Comment by lindingkang** [comment]
这个之前也试过了，还是没有改变这个同样的报错

**Comment by DongboShi** [comment]
git clone成功了吗

**Comment by lindingkang** [comment]
之前git clone成功了，git push也成功了。但git pull连不上后改了ip和端口，之后就这仨都不行了

**Comment by DongboShi** [comment]
git端口默认是9418

**Comment by DongboShi** [comment]
git pull之前连不上可能是因为网络不稳定

**Comment by DongboShi** [comment]
git config --global --unset http.proxys然后检查一下你的.gitconfig文件

**Comment by DongboShi** [comment]
然后git clone的时候使用ssh那个链接

**Comment by chenjiancqu** [comment]
git config --global --list
检查一下所有全局配置。确保代理设置是正确的。

**Comment by lindingkang** [comment]
这个文件目前这样
![image](https://github.com/DongboShi/bigdata_econ/assets/152069389/9a5dc210-c93f-4e41-b0da-ca8edde93cbf)

**Comment by lindingkang** [comment]
![image](https://github.com/DongboShi/bigdata_econ/assets/152069389/bba24137-4307-45c0-8ce0-b14991e14551)

**Comment by chenjiancqu** [comment]
git config --global --unset http.https
git config --global --unset https.https

删除或重置代理设置

**Comment by lindingkang** [comment]
我刚刚尝试把这个.gitconfig文件下面的那两个网址给删了，然后就可以了。现在git push 和git pull都可以连接上了。谢谢两位老师。
