### ISSUE TITLE
拼接HTTP请求URL失败

### ISSUE THREAD

**Issue by duxy97** [DongboShi/bigdata_econ#30]
1. 参考PPT上的拼接HTTP请求URL的代码
<img width="597" alt="dba27fd6a76f1fe31b2fb8ff23ccd2e" src="https://github.com/DongboShi/bigdata_econ/assets/151997690/f5a04cc5-7b4b-4f11-9c17-ea98732ef5a1">

2. 在python上面运行如下代码
![93ea293802794cfa57ec34405603a6c](https://github.com/DongboShi/bigdata_econ/assets/151997690/e146fff8-38f4-45d5-abb0-f7ceb32609e6)

3. 运行结果显示如下
![e11c9a9aa035ac74abf8a80f13a67a6](https://github.com/DongboShi/bigdata_econ/assets/151997690/29bda148-be21-4d22-9a51-94dbf171ac5c)

4. 上面运行结果中的链接点开显示：
<img width="157" alt="09f8464c3bf7edb612ba0f20b888416" src="https://github.com/DongboShi/bigdata_econ/assets/151997690/f8eb89e0-3249-424f-8d4d-4bd5bcb008b5">

5. 找到高德地图官网 https://lbs.amap.com/api/javascript-api/guide/abc/prepare 显示：
 {添加成功后，可获取到key值和安全密钥jscode（自2021年12月02日升级，升级之后所申请的 key 必须配备安全密钥 jscode 一起使用)
注意：此次升级不会影响之前已获得 key 的使用；升级之后的新增的key必须要配备安全密钥一起使用，具体用法请您参看下文《JSAPI key和安全密钥设置和使用》（本次key升级新增安全密钥，是为了提升广大用户的对自己的key安全有效管理，降低明文传输被窃取的风险 。}

6. 官网新的设置方法我们没看懂要怎么做

**Comment by fanzhang9911** [comment]
同学你好，5.中的连接是另一个API接口，它提供了诸如绘制地图的更多功能，但如果是获取数据的话，还是选择”web 服务API“更加方便。麻烦你检查一下添加key的时候，有没有选错服务平台

**Comment by zhazhadz** [comment]
我也遇到了是相同的问题，返回不出任何值我选的确实是web服务

**Comment by zhazhadz** [comment]
找到问题了，因为没有在Python解释器无法找到requests模块导致的，装个requests模块就可以

**Comment by fanzhang9911** [comment]
正解，url请求需要导入库，Python有两个库可以做url请求，一个内置库urllib，还有一个是第三方库request（常用这个）。
