### ISSUE TITLE
Debian工作路径和setwd工作路径不一致怎么解决

### ISSUE THREAD

**Issue by hahasyj** [DongboShi/bigdata_econ#31]
Debian在Linux中，setwd中在C盘某处，怎么解决这个问题，后续无法在命令行进行操作
![c4a0cdda22e56222a7d7aae85438f74](https://github.com/DongboShi/bigdata_econ/assets/152355780/65773b4d-8d51-47ea-a896-78b6ecc3548a)

**Comment by DongboShi** [comment]
wsl可以识别你的路径
