### ISSUE TITLE
没有明白怎么使用命令行执行python文件

### ISSUE THREAD

**Issue by lindingkang** [DongboShi/bigdata_econ#32]
作业的第二题，不知道怎么在命令行当中直接使用.py脚本，也不知道怎么能把文件的那个参数传递进去。
我的脚本`read_patents_return_df.py`为：
`import json`  
`import pandas as pd`  
`def read_patents_return_df(file):`
`    publication_number = []`
`    filing_date = []`
`    publication_date = []`
`    grant_date = []`
`    priority_date = []`
`    with open(file,"r") as f:`
`        for pt in f.readlines():`
`            patent = json.loads(pt)`
`            publication_number.append(patent["publication_number"])`
`            filing_date.append(patent["filing_date"])`
`            publication_date.append(patent["publication_date"])`
`            grant_date.append(patent["grant_date"])`
`            priority_date.append(patent["priority_date"])`
`    return` `pd.DataFrame({"publication_number":publication_number,"filing_date":filing_date,"publication_date":publication_date,"grant_date":grant_date,"priority_date":priority_date})
`
我在命令行中首先像R一样，赋予了更高权限：
`chmod +x read_patents_return_df.py`
然后我尝试这样执行：
`./read_patents_return_df.py google100.txt`
报错为:
`./read_patents_return_df.py: line 6: $'\r\nCreated on Sat Dec  9 18:25:33 2023\r\n\r\n@author: 林北鸣\r\n\r': command not found`
`./read_patents_return_df.py: line 7: $'\r': command not found`
`./read_patents_return_df.py: line 8: import: command not found`
`./read_patents_return_df.py: line 9: import: command not found`
`./read_patents_return_df.py: line 10: syntax error near unexpected token '('`
`'/read_patents_return_df.py: line 10: 'def read_patents_return_df(file):'`

接着我尝试用这样执行：
`python3 read_patents_return_df.py google100.txt`
报错为：
`Traceback (most recent call last):`
`  File "/home/penpen/read_patents_return_df.py", line 9, in <module>`
`    import pandas as pd`
`ModuleNotFoundError: No module named 'pandas'`

**Comment by hanxiake000** [comment]
python中用sys模块中的argv函数来获取命令行参数，argv[1]表示第一个参数。参考：
https://zhuanlan.zhihu.com/p/378896661

**Comment by hanxiake000** [comment]
另外py文件第一行要加上“#! /usr/bin/env python3”，不然命令行没法识别这是python代码，所以就找不到import命令

**Comment by DongboShi** [comment]
或者直接用python3 执行

**Comment by lindingkang** [comment]
> python中用sys模块中的argv函数来获取命令行参数，argv[1]表示第一个参数。参考： https://zhuanlan.zhihu.com/p/378896661

非常感谢！
使用sys.arg函数可能不能更详细地定义参数，我遇到了这样的问题导致传递进去文件地址的时候，直接把这个字符串当成了一个变量。使用argparse文件可以解决这个问题，可以定义每个传入参数的类型。
```
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('file')
args = parser.parse_args()
file = args.file
```
