### ISSUE TITLE
关于MacOS的PyCharm无法安装 requests

### ISSUE THREAD

**Issue by huang-zhiming** [DongboShi/bigdata_econ#33]
在拼接url时遇到和[https://github.com/DongboShi/bigdata_econ/issues/30](url)一样的问题，怀疑是没有安装requests
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/6b129cf1-9428-40eb-8a2e-842c29e3c143)

```python
import requests
``` 
显示导入模组失败
/ModuleNotFoundError: No module named 'requests'
已尝试方法：
在iterms2中安装
/# hwangtsimin @ MacBook-Air in ~ 
$ brew install python-requests
iterms2中已安装成功，但是PyCharm中仍然显示”无此模组“

**Comment by hanxiake000** [comment]
wsl2也有同样问题，debian中安装了requests（命令：sudo apt-get install python3-requests），但是pycharm运行时仍报错没有requests模块

**Comment by DongboShi** [comment]
试一下 brew install python3-requests

> 在拼接url时遇到和[https://github.com/DongboShi/bigdata_econ/issues/30](url)一样的问题，怀疑是没有安装requests ![image](https://private-user-images.githubusercontent.com/152162958/289275695-6b129cf1-9428-40eb-8a2e-842c29e3c143.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNjYyNzUsIm5iZiI6MTcwMjE2NTk3NSwicGF0aCI6Ii8xNTIxNjI5NTgvMjg5Mjc1Njk1LTZiMTI5Y2YxLTk0MjgtNDBlYi04YTJlLTg0MmMyOWUzYzE0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQyMzUyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzFkY2VkNzBjMTllOGM1YWRkYTQxZTA1MGU5YWZhY2E4YmQyZTIyN2VjYjM1MjkwMGM4YWRhNjgyMWM2MWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Urreh2ssyODf9zrtG49nEbiDw0MoonSEF7IKhdCcCBc)
> 
> ```python
> import requests
> ```
> 
> 显示导入模组失败 /ModuleNotFoundError: No module named 'requests' 已尝试方法： 在iterms2中安装 /# hwangtsimin @ MacBook-Air in ~ $ brew install python-requests iterms2中已安装成功，但是PyCharm中仍然显示”无此模组“

**Comment by DongboShi** [comment]
> sudo apt-get install python3-requests

在wsl命令行可以导入requests吗

**Comment by DongboShi** [comment]
> 试一下 brew install python3-requests
> 
> > 在拼接url时遇到和[https://github.com/DongboShi/bigdata_econ/issues/30](url)一样的问题，怀疑是没有安装requests ![image](https://private-user-images.githubusercontent.com/152162958/289275695-6b129cf1-9428-40eb-8a2e-842c29e3c143.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNjYyNzUsIm5iZiI6MTcwMjE2NTk3NSwicGF0aCI6Ii8xNTIxNjI5NTgvMjg5Mjc1Njk1LTZiMTI5Y2YxLTk0MjgtNDBlYi04YTJlLTg0MmMyOWUzYzE0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQyMzUyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzFkY2VkNzBjMTllOGM1YWRkYTQxZTA1MGU5YWZhY2E4YmQyZTIyN2VjYjM1MjkwMGM4YWRhNjgyMWM2MWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Urreh2ssyODf9zrtG49nEbiDw0MoonSEF7IKhdCcCBc)
> > ```python
> > import requests
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 显示导入模组失败 /ModuleNotFoundError: No module named 'requests' 已尝试方法： 在iterms2中安装 /# hwangtsimin @ MacBook-Air in ~ $ brew install python-requests iterms2中已安装成功，但是PyCharm中仍然显示”无此模组“
还有就是brew 有没有报错

**Comment by huang-zhiming** [comment]
brew 在安装时没有报错，刚刚试了下brew install Python3-requests, 显示没有这种名称的casks
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/5ac280fb-c5a3-4ba5-bc77-423fd3fadbd0)

**Comment by DongboShi** [comment]
brew search python
看一下你有几个python

**Comment by huang-zhiming** [comment]
只有一个吧
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/f1e859e4-4421-4a9f-ae5f-d2903ac26f02)
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/cf49a1e3-a147-4817-a51c-5ca0b4d161b5)

**Comment by DongboShi** [comment]
你运行brew search python

**Comment by huang-zhiming** [comment]
```python
# hwangtsimin @ MacBook-Air in ~ [8:44:23]
$ brew search python
==> Formulae
app-engine-python                        python-matplotlib
boost-python3                            python-mdurl
bpython                                  python-mpmath
cyclonedx-python                         python-msgpack
ipython                                  python-mutagen
meson-python                             python-networkx
micropython                              python-oauthlib
ptpython                                 python-openapi3
python-abseil                            python-packaging
python-anytree                           python-pathspec
python-argcomplete                       python-pbr
python-asn1crypto                        python-platformdirs
python-attrs                             python-pluggy
python-boto3                             python-ply
python-botocore                          python-prompt-toolkit
python-brotli                            python-psutil
python-build                             python-pycurl
python-cachetools                        python-pyparsing
python-certifi ✔                         python-pyproject-hooks
python-chardet                           python-pytz
python-charset-normalizer ✔              python-regex
python-cli-helpers                       python-requests ✔
python-click                             python-requests-oauthlib
python-colorama                          python-rich
python-configargparse                    python-s3transfer
python-configobj                         python-setuptools
python-cryptography                      python-setuptools-scm
python-cycler                            python-sympy
python-dateutil                          python-tabulate
python-dicttoxml                         python-termcolor
python-distlib                           python-tk@3.10
python-distro                            python-tk@3.11
python-docopt                            python-tk@3.12
python-filelock                          python-tk@3.9
python-flit-core                         python-toml
python-gdbm@3.11                         python-trove-classifiers
python-gdbm@3.12                         python-typing-extensions
python-hatch-fancy-pypi-readme           python-urllib3 ✔
python-hatch-vcs                         python-wcwidth
python-hatchling                         python-websocket-client
python-idna ✔                            python-xlsxwriter
python-jinja                             python-yq
python-jmespath                          python@3.10
python-json5                             python@3.11 ✔
python-kiwisolver                        python@3.12
python-launcher                          python@3.7
python-lsp-server                        python@3.8
python-lxml                              python@3.9
python-magic                             reorder-python-imports
python-mako                              wxpython
python-markdown                          pythran
python-markdown-it-py                    jython
python-markupsafe                        cython

==> Casks
mysql-connector-python
```

**Comment by DongboShi** [comment]
所以你看你装了多少python

**Comment by DongboShi** [comment]
目前看起来是把包装到了python3.11而你运行的软链接是别的版本的python

**Comment by huang-zhiming** [comment]
好的，谢谢老师，我试试删除旧的版本，确保终端配置文件引用新版本

**Comment by huang-zhiming** [comment]
使用“pip install requests"命令已解决无法在Pycharm安装requests的问题
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/329ccc82-de0f-4e5b-91af-3cc34d3dd00b)
