### ISSUE TITLE
在mysql官网无法找到mysql-server_MVER-DVER_CPU.deb-bundle.tar. MVER的下载文件，用MySQL APT安装也无法安装

### ISSUE THREAD

**Issue by lindingkang** [DongboShi/bigdata_econ#34]
1.在mysql的2.5.5教程中，下载不同mysql安装包的网站https://dev.mysql.com/downloads/中没有mysql-server_MVER-DVER_CPU.deb-bundle.tar. MVER类似的文件。
![image](https://github.com/DongboShi/bigdata_econ/assets/152069389/c02f70aa-b3d5-4e59-bcd8-f9885bc291c8)
2.使用官网的https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/教程通过MySQL APT安装，命令
` sudo dpkg -i ~/mysql/mysql-apt-config_0.8.28-1_all.deb`之后，报错，缺失必要的包
`dpkg: regarding .../mysql-apt-config_0.8.28-1_all.deb containing mysql-apt-config, pre-dependency problem:`
 `mysql-apt-config pre-depends on lsb-release`
 ` lsb-release is not installed.`

`dpkg: error processing archive /home/penpen/mysql/mysql-apt-config_0.8.28-1_all.deb (--install):`
` pre-dependency problem - not installing mysql-apt-config`
`Errors were encountered while processing:`
 `/home/penpen/mysql/mysql-apt-config_0.8.28-1_all.deb`
这两个包也无法用apt-get安装。

**Comment by maxwelldemon5119** [comment]
我也是这个报错，但是我在sudo apt-get update后用sudo apt-get -y install lsb-release安上了这个包，之后运行 sudo dpkg -i ~/mysql/mysql-apt-config_0.8.28-1_all.deb成功。或许你可以update一下？

**Comment by hanxiake000** [comment]
这里点开有
![1702375904397](https://github.com/DongboShi/bigdata_econ/assets/151877272/cec35c8a-e1fb-4af9-811a-b3bd7d319ec1)
