### ISSUE TITLE
第四讲作业ppt中存在笔误

### ISSUE THREAD

**Issue by zhazhadz** [DongboShi/bigdata_econ#35]
作业第二题中filling date 应该改成 filing data，文档中没有filling data这一项。
<img width="396" alt="1" src="https://github.com/DongboShi/bigdata_econ/assets/151952519/246b552f-4367-4b18-8709-49eef0a5684a">

**Comment by hanxiake000** [comment]
应该没错吧，就是filling date 申请日，文件中的字段名加了连字符filling_date

**Comment by zhazhadz** [comment]
<img width="764" alt="1702382754705" src="https://github.com/DongboShi/bigdata_econ/assets/151952519/f008919d-7737-428b-9ff0-1b4abfc04aac">
txt里面是filing data
