### ISSUE TITLE
关于本地编辑器无法推送文件至GitHub仓库问题一：执行”git add ."命令报错

### ISSUE THREAD

**Issue by huang-zhiming** [DongboShi/bigdata_econ#5]
问题描述：
按照第2章讲义，执行“git add .”命令时报错，报错内容“'learn_git/' does not have a commit checked out”。
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/2a557ad2-021d-48c2-bb28-5b5b177ff196)

**Comment by DongboShi** [comment]
输入一下git status会给你提示的你有一个commit没有完成

**Comment by huang-zhiming** [comment]
这个结果我看不懂，我再琢磨琢磨吧=。=
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/968523ee-6c89-4a97-a1fc-466cc4344d13)

**Comment by DongboShi** [comment]
明白了，你看下是不是有一个.文件夹在你的路径里面。参考这个https://stackoverflow.com/questions/56873278/how-to-fix-error-filename-does-not-have-a-commit-checked-out-fatal-adding

**Comment by huang-zhiming** [comment]
文件夹的子目录中确实有后缀为".git"的文件，删除后运行“git add ."不报错了，但文件推送到GitHub仓库仍然失败，这是一个新问题，我另起一个问题单。
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/281abc2d-643f-45ab-ba54-5138cbf4b102)
