### ISSUE TITLE
本地文件push不上github

### ISSUE THREAD

**Issue by hanxiake000** [DongboShi/bigdata_econ#6]
输入git push 以后，让填写用户名和密码，填完以后出现如下问题，push不上去。

![微信图片_20231128014751](https://github.com/DongboShi/bigdata_econ/assets/151877272/9c67d5e4-8e82-44f5-a58a-ce84f390801a)

**Comment by DongboShi** [comment]
授权有问题，项目没有权限push

**Comment by hanxiake000** [comment]
> 授权有问题，项目没有权限push

是github中仓库的权限设置吗？如何修改权限？

**Comment by Jinpoli** [comment]
我看似乎要搞个token啥的，我试了一下，似乎可以，但还是不知道怎么就push成功了……
https://blog.csdn.net/weixin_43452467/article/details/121704661

**Comment by hanxiake000** [comment]
> 我看似乎要搞个token啥的，我试了一下，似乎可以，但还是不知道怎么就push成功了…… https://blog.csdn.net/weixin_43452467/article/details/121704661

成功啦！！感谢！！

**Comment by zhazhadz** [comment]
你这个git clone的时候用的是http协议，Github删除了使用username-password组合的选项，看这个git写的官方说明https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/，最好的git clone 用ssh协议

**Comment by hanxiake000** [comment]
> 你这个git clone的时候用的是http协议，Github删除了使用username-password组合的选项，看这个git写的官方说明[https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/，最好的git](https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/%EF%BC%8C%E6%9C%80%E5%A5%BD%E7%9A%84git) clone 用ssh协议

试了一下ssh，果然更好用！谢谢！
