### ISSUE TITLE
关于本地编辑器无法推送文件至GitHub仓库问题二：git push >> fatal: no configured push destination

### ISSUE THREAD

**Issue by huang-zhiming** [DongboShi/bigdata_econ#7]
问题描述：
在已经执行”git clone"命令，本地与GitHub仓库已经建立连接之后，执行“git push"命令失败，显示：”fatal: no configured push destination“
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/3270a8b0-715d-4678-81c5-4dc32efa089f)

**Comment by DongboShi** [comment]
你之前clone过了吧，delete the folder and do the git clone again

**Comment by huang-zhiming** [comment]
a new issue occurred after deleting the local repository and re-git-clone
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/aa14e0bb-9f64-436d-88cf-64efeec6e1a3)

**Comment by huang-zhiming** [comment]
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/bba51b9d-ff8f-45df-afe5-6f9d1222b333)
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/5a8a3b26-51ab-47dd-8001-a439da2b21e5)
![image](https://github.com/DongboShi/bigdata_econ/assets/152162958/ca18415a-fb47-4fa9-812a-2d0589652192)

**Comment by huang-zhiming** [comment]
Use SSH instead of HTTPS with the command "git remote set-url origin +SSH（在remote repository code那里找）" 解决了频繁operation timed out的问题。
