### ISSUE TITLE
讲义中的问题

### ISSUE THREAD

**Issue by JiLisx** [DongboShi/bigdata_econ#8]
##  2.5.5 Git目前的局限性
原文： ”另一种方式是退而求其次，使用LeTex编辑文件“
错别字：`LeTex`应改为`LaTex`

##  3.3.1 安装R
1. URL 点开是404
2. 这部分`apt brew`这一行的显示有问题

**Comment by DongboShi** [comment]
谢谢~ URL可能过期了，我更新一下吧
