### ISSUE TITLE
git pull 失败提示 Connection reset by peer

### ISSUE THREAD

**Issue by qzhu527** [DongboShi/bigdata_econ#9]
git pull 失败, 显示的错误提示是 fatal: unable to access 'https://github.com/DongboShi/bigdata_econ.git/': error:02FFF036:system library:func(4095):Connection reset by peer， 初步搜索了一下，没有找到解决方案。

多试了几次git pull ，还会出现以下错误提示：
fatal: unable to access 'https://github.com/DongboShi/bigdata_econ.git/': HTTP/2 stream 1 was not closed cleanly before end of the underlying stream

<img width="1077" alt="截屏2023-11-28 19 55 58" src="https://github.com/DongboShi/bigdata_econ/assets/152081225/79accb16-02bb-4ed7-95d7-1a011debab4e">

**Comment by DongboShi** [comment]
clone过吗

**Comment by qzhu527** [comment]
<img width="1195" alt="截屏2023-11-28 20 10 59" src="https://github.com/DongboShi/bigdata_econ/assets/152081225/8f2330a3-a19b-4bc3-ae30-232b7e873189">
clone 过

**Comment by DongboShi** [comment]
看上去是网络的问题，换个网试试
